DROP TABLE IF EXISTS MEMBER;
CREATE TABLE IF NOT EXISTS MEMBER (
	OID 		INTEGER GENERATED ALWAYS AS IDENTITY,
	ACCOUNT		VARCHAR NOT NULL UNIQUE,
	PW			VARCHAR NOT NULL,
	EMAIL		VARCHAR NOT NULL,
	CRETAEDAT	TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	MODIFIEDAT	TIMESTAMP DEFAULT NULL,
	IS_DELETE	VARCHAR DEFAULT 'N' CHECK (IS_DELETE IN ('Y', 'N')),
	DELETEDAT	TIMESTAMP DEFAULT NULL
)